### PR TITLE
Open Graph tags

### PR DESCRIPTION
**Pull request by chrismytton**
This adds some default Open Graph tags to all pages on the website. It also adds specific Open Graph tags for Organizations, Places and blog posts.

Fixes https://github.com/mysociety/pombola/issues/2047
Fixes https://github.com/mysociety/pombola/issues/2048
Fixes https://github.com/mysociety/pombola/issues/1956
Fixes https://github.com/mysociety/pombola/issues/1955

### CODE REVIEW

**Comment by mhl** [comment]
I think using `og:type` of `profile` is right for `Person` but not `Organisation` and `Place`. There is a `place` type, but I'm not sure what's right for `Organisation`.

**Comment by mhl** [comment]
I've left a few comments which would be worth addressing, but this looks good.

Could you also squash this down into fewer commits? (Some are essentially fixups to earlier commits - e.g. perhaps just one for everything to do with people, one for places, etc.)

**Comment by chrismytton** [comment]
@mhl I've fixed the things in your comments so I think this is ready to go now.

**Comment by mhl** [comment]
@chrismytton Sorry to say this at this stage, but I think these could really easily be broken without us noticing in the future - could you add some tests to check that the expected tags are returned for each page?

**Comment by chrismytton** [comment]
Tests added, commits rebased. Once Travis is happy I'll get this merged/deployed.

**Comment by chrismytton** [comment]
Oh dear, accidentally merged with a WIP commit which I had to sneak past the update hook on git.mysociety.org, sorry! :disappointed:

**Comment by chrismytton** [comment]
This is how it looks on the live sites:

screen shot 2016-03-11 at 12 46 17

**Pull request merged**
