### PR TITLE
Models can define fields to be whitespace stripped

### PR DESCRIPTION
**Pull request by chrismytton**
This adds a 'fields_to_whitespace_normalize' property to models which
can be set to a list of fields which should have their whitespace
removed before the model is saved.

First part of #1866

### CODE REVIEW

**Comment by mhl** [comment]
Looks good so far, I guess you're going to add lots of other fields to be normalized as well.

It'd be good to also do `re.sub(r'(?ms)\s+', ' ')` as part of normalizing the whitespace too...

**Comment by chrismytton** [comment]
> It'd be good to also do re.sub(r'(?ms)\s+', ' ') as part of normalizing the whitespace too...

Ooh, yes good idea!

**Comment by chrismytton** [comment]
@mhl I've added the regex you suggested and defined some more fields to have their whitespace normalized, so I think this is ready to go now!

**Comment by mhl** [comment]
LGTM :+1:

**Pull request merged**
