### PR TITLE
Person attendance: Change wording & clarify methodology

### PR DESCRIPTION
**Pull request by xybrnet**
Person attendance page:
Changed MINISTER to read MINISTRY, and added some notes on the attendance methodology.

@mhl

### CODE REVIEW

**Comment by mhl** [comment]
Hi @xybrnet - just to check, is it really correct to have this wording on a minister's page?

> 2016 COMMITTEE ATTENDANCE AS MINISTRY

It seems very odd to me to say that a person can have a role as a "ministry"!

**Comment by mhl** [comment]
(Incidentally, if you rebase over current master then the spurious test errors should be gone - we had to make some updates now that Travis is using a trusty build environment.)

**Comment by xybrnet** [comment]
Hi @mhl - thanks, I've rebased with master.

I find the wording a bit weird too - but it is what they requested. I'll ask someone one our side to just confirm with them tomorrow, and get back to you.

**Comment by xybrnet** [comment]
@mhl 
I was away last week, and this seems to had gotten lost.
I've updated the wording to read MINISTER/DEPUTY as confirmed with People's Assembly.

**Comment by mhl** [comment]
:+1: Sorry about the delay, I'll merge and deploy this now.

**Pull request merged**
