### PR TITLE
ZA: new constituency data and accompanying changes (revised)

### PR DESCRIPTION
**Pull request by mhl**
A revised version of @geoffkilpin's pull request here: https://github.com/mysociety/pombola/pull/1593

### CODE REVIEW

**Comment by geoffkilpin** [comment]
Hi @mhl - many thanks for all the changes you've made here. Unfortunately I've run out of time to look into one or two issues, noted below:

* The large number of locations that are not found [listed](https://gist.github.com/mhl/9b2049e6398626d9713b) by the update script is very surprising - I got this down to zero (excluding offices with no address), so will need to see what is going wrong
* Likewise, there should be no unmatched people names
* I'm going to look at the ```convert_to_import_json.py``` output script diff a bit more closely - the change looks a bit odd
* I've gone through your code changes and found no issues - thanks very much for cleaning everything up!

**Comment by mhl** [comment]
@geoffkilpin When I ran it on the staging site the results for location lookup failures were much better:

```
People not found
ANC Constituency Office (214): Hazyview (Office Is Relocating) 	Pat Ngomane
ANC Constituency Office (414): Ramotshere Moiloa 	Olefile Sehako
ANC Constituency Office (504): Kathu 	Tshoganetso Mpho Adolphina Gasebonwe
DA Constituency Area: Midrand East 	Dion Travers George
DA Constituency Area: Limpopo North Central (Giyani / Greater Letaba / Thulamela) 	Mmoba Solomon Seshoka
Locations not found
ANC Constituency Office (308): Elim 	NEW OFFICE - Address to be confirmed, South Africa

ANC Constituency Office (317): Rita 	TBA

ANC Constituency Office (337): Fetakgomo 	NEW OFFICE- Address to be confirmed, South Africa

ANC Constituency Office (356): Gamaja 	NEW OFFICE- address still to be confirmed, South Africa

ANC Constituency Office (000): Matsulu (New Office To Be Opened) 	TBA

ANC Constituency Office (679): Makhasa 	TBA
```

... so they may have been transient geocoding failures. I'm not sure why the name resolution would have been different, though - I'll check through my changes.

**Comment by geoffkilpin** [comment]
Apologies for the delayed response from my side @mhl.

Regarding the names: despite what I said above, I have remembered that the first two (Pat Ngomane and Olefile Sehako) I left to be manual corrections following the import (we worked out what the corrections were quite late and an odd but isolated git issue I was experiencing made this more time efficient). 

In the case of the other three names it seems the legal names for those individuals had been edited on the PA site. I've corrected these to use the correct legal name (moving the edited preferred name to be the 'name to use' alternative name).

I have taken a closer look at your diff after running ```convert_to_import_json.py``` and have concluded there isn't any material change here - it's a bit odd that some data has been rearranged but it shouldn't make a difference.

This should mean that we are ok to import, with person matching failures for Pat Ngomane and Olefile Sehako expected.

**Comment by mhl** [comment]
Thanks very much, @geoffkilpin - I've run that on the live server (just the two unresolved names you mentioned) so I hope that's all fine.

**Comment by geoffkilpin** [comment]
Many thanks @mhl - so far looking great! I've manually corrected the two unresolved names.

**Pull request merged**
