### PR TITLE
Switch to container-based builds on Travis

### PR DESCRIPTION
**Pull request by mhl**
The "sudo: false" means that Travis will try to run to run its test on
their new container-based infrastructure. This means that builds will
be much faster to start up, which will hopefully remove a lot of
frustration with waiting for tests to run on the old infrastructure.
    
Note that this removes the Python GDAL requirement, which it turns out
is not required anyway and creates problems on container-based builds
on Travis. [1]  (It was only there for MapIt, but it's not required
by MapIt either - Django's code calls the C library directly.)  Thanks
to Matthew Somerville (@dracos) for pointing this out.  Futher helpful
background from him and @jennyd on the complicated situation with the
Python GDAL bindings can be found here:
    
  https://github.com/alphagov/mapit/commit/2908cda3
    
[1] https://github.com/travis-ci/travis-ci/issues/2401

### CODE REVIEW

**Comment by mhl** [comment]
Unfortunately, I think this is effectively blocked until this PR from @dracos is merged by Travis:

* https://github.com/travis-ci/travis-cookbooks/pull/500

**Comment by mhl** [comment]
Although, reading that again, maybe it'll work if I remove `gdal-bin`

**Comment by mhl** [comment]
Nope, it still wants to remove postgis:

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libgdal-dev yui-compressor
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  java-wrappers libcurl3-gnutls libcurl4-gnutls-dev libdap-dev libdapserver7
  libgdal1h libgif-dev libhdf4-alt-dev libhdf5-serial-dev libjargs-java
  libnetcdf-dev libspatialite-dev libspatialite5 libxerces-c-dev
  libxerces-c3.1 unixodbc unixodbc-dev uuid-dev
Suggested packages:
  libcurl3-dbg libgdal-doc libhdf5-doc libjargs-java-doc netcdf-bin netcdf-doc
  libxerces-c-doc
The following packages will be REMOVED:
  libcurl4-openssl-dev libgdal1 postgresql-9.1-postgis-2.1
  postgresql-9.2-postgis-2.1 postgresql-9.3-postgis-2.1
  postgresql-9.4-postgis-2.1
The following NEW packages will be installed:
  java-wrappers libcurl4-gnutls-dev libdap-dev libdapserver7 libgdal-dev
  libgdal1h libgif-dev libhdf4-alt-dev libhdf5-serial-dev libjargs-java
  libnetcdf-dev libspatialite-dev libspatialite5 libxerces-c-dev
  libxerces-c3.1 unixodbc unixodbc-dev uuid-dev yui-compressor
The following packages will be upgraded:
  libcurl3-gnutls
1 upgraded, 19 newly installed, 6 to remove and 214 not upgraded.
Need to get 25.5 MB of archives.
```

**Comment by chrismytton** [comment]
Now we're running on the container based infrastructure we can also take advantage of [Travis' pip caching](https://docs.travis-ci.com/user/caching/#pip-cache), which should give a decent speed boost to the actual runtime of the tests.

**Comment by chrismytton** [comment]
Woohoo, great work @mhl! :sparkles: :+1:

**Pull request merged**
