### PR TITLE
[KE] Show politician responsibilities on Mzalendo profile pages

### LINKED ISSUE #2304: [KE] Show "Responsibilities" for a representative, near their contact details on their profile page
It is a waste of everybody’s time for Mzalendo visitors to contact representatives about issues the representative has no influence over.

Different types of representatives have different responsibilities. From Jessica:
* Members of the National Assembly (MNAs): Representation, Oversight, Legislation and CDF Management
* All other types of MNAs (nominated & women reps): Representation, Oversight and Legislation only
* Senators: Representation, Oversight and Legislation with county interests in mind.

Make these responsibilities clear on the person page, near the contact details.

### PR DESCRIPTION
**Pull request by zarino**
Fixes #2304.

screen shot 2017-10-26 at 14 29 06

### CODE REVIEW

**Comment by jacksonj04** [comment]
screen shot 2017-10-26 at 14 29 06

**Comment by zarino** [comment]
@JenMysoc @jacksonj04 Shall we get this deployed onto a staging server, with the responsibilities text added to the database, so Jessica can check she’s happy with it?

**Comment by JenMysoc** [comment]
Yes please!

**Comment by zarino** [comment]
Feedback from Jessica:

> The placement of the new responsibilities makes sense, but could we have a different background for it. A pale red background would do.

**Pull request merged**
