### PR TITLE
Removing items from blog menu dropdown on pa.org.za

### LINKED ISSUE #1919: [ZA] Remove "Impressions" and "Elections 2014" from Blog Menu Item
PMG would like to remove the links to Impressions and Elections 2014 from the Blog menu item. They would like to fold the posts from these sections into the "That Week in Parliament" section.

### PR DESCRIPTION
**Pull request by JenMysoc**
Removing Impressions and Elections 2014 from the Blog menu drop down items on people's assembly

Fixes #1919

### CODE REVIEW

**Comment by mhl** [comment]
This commit looks good :+1:  Just to check, who is going to add the "That Week in Parliament" category to the existing "Impressions" and "Elections 2014" posts?

**Comment by JenMysoc** [comment]
@mhl Is that something that's done in the admin area? Or in the code?

**Comment by mhl** [comment]
We discussed this in a hangout, but for the record here: I meant adding categories in the admin. However, when we looked through there were so many posts in the category "Impressions" and "Elections 2014" that it makes more sense to do this programmatically:

```python
that_week_category = Category.objects.get(name='That Week In Parliament')
for ip in InfoPage.objects.filter(categories__slug='impressions'):
    ip.categories.add(that_week_category)
for ip in InfoPage.objects.filter(categories__slug='elections-2014'):
    ip.categories.add(that_week_category)
```

**Comment by JenMysoc** [comment]
Actually I've done it as a lot of them were already also labelled "that week in parliament" so it wasn't too much work in the end :)

**Comment by mhl** [comment]
Great, that's deployed now.

**Pull request merged**
